<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-975I42U" failures="1" tests="7" name="TestNG.TestNG_HardAsserts" time="0.053" errors="0" timestamp="2023-08-08T16:11:06 IST" skipped="0">
  <testcase classname="TestNG.TestNG_HardAsserts" name="test6" time="0.006">
    <system-out>
      <![CDATA[running test6 method]]>
    </system-out>
  </testcase> <!-- test6 -->
  <testcase classname="TestNG.TestNG_HardAsserts" name="Test2" time="0.003">
    <system-out>
      <![CDATA[Running Test2 method]]>
    </system-out>
  </testcase> <!-- Test2 -->
  <testcase classname="TestNG.TestNG_HardAsserts" name="Test4" time="0.004">
    <system-out>
      <![CDATA[Running Test4 method]]>
    </system-out>
  </testcase> <!-- Test4 -->
  <testcase classname="TestNG.TestNG_HardAsserts" name="Test5" time="0.003">
    <system-out>
      <![CDATA[Running Test5 method]]>
    </system-out>
  </testcase> <!-- Test5 -->
  <testcase classname="TestNG.TestNG_HardAsserts" name="Test3" time="0.003">
    <system-out>
      <![CDATA[Running Test3 method]]>
    </system-out>
  </testcase> <!-- Test3 -->
  <testcase classname="TestNG.TestNG_HardAsserts" name="test7" time="0.007">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at TestNG.TestNG_HardAsserts.test7(TestNG_HardAsserts.java:74)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[running test7 method]]>
    </system-out>
  </testcase> <!-- test7 -->
  <testcase classname="TestNG.TestNG_HardAsserts" name="Test1" time="0.027">
    <system-out>
      <![CDATA[Running Test1 method]]>
    </system-out>
  </testcase> <!-- Test1 -->
  <system-out>
    <![CDATA[Running Test1 method
Running Test2 method
Running Test3 method
Running Test4 method
Running Test5 method
running test6 method
running test7 method]]>
  </system-out>
</testsuite> <!-- TestNG.TestNG_HardAsserts -->
